<?php
/*
$PAGES=Array();
$PAGES[]=['auth','Авторизация',false];
$PAGES[]=['reg','Регистрация',false];
$PAGES[]=['group','Группы',true];
$PAGES[]=['projects','Проекты',true];
$PAGES[]=['main','Задачи',true];
*/